AWSTemplateFormatVersion: '2010-09-09'
Transform: 'AWS::Serverless-2016-10-31'

Resources:

  DeaTeatroFunction:
    Type: 'AWS::Serverless::Function'
    Properties:
      Handler: handler.deaTeatro
      Runtime: nodejs14.x
      CodeUri: .   
  
  DeaTeatroInvokePermission:
    Type: 'AWS::Lambda::Permission'
    Properties:
      Action: 'lambda:InvokeFunction'
      FunctionName: !Ref DeaTeatroFunction
      Principal: events.amazonaws.com
      SourceArn: !GetAtt MyEventsRule.Arn

  MyEventsRule:
    Type: 'AWS::Events::Rule'
    Properties:
      Description: "Order to DeaTeatro"
      EventPattern: 
        source:
          - custom.orderManager
        detail-type:
          - order                
        detail:
          ticketEventName:
            - "DeaTeatro"
      Targets:
        - Arn: !GetAtt DeaTeatroFunction.Arn
          Id: "RuleId"